module.exports = [{
  header: `Schedule triggers with different sources for events`,
  para: [`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque in libero eu nunc gravida laoreet. Sed est diam, lobortis vel dignissim et, finibus quis odio. Pellentesque sed nunc ipsum. Cras quis mi ac est tempus laoreet. Sed vel eros id lacus laoreet feugiat. Mauris vel ante sed nunc varius scelerisque ac vitae quam. Donec tempor, dui nec pretium sollicitudin, nibh felis luctus eros, id rhoncus neque est vel nunc. Nulla at odio eget dui dictum elementum in sit amet sem. In non nulla in diam lobortis faucibus. Vivamus viverra risus leo, vel porta nisi efficitur ac. Donec eu dignissim neque.`],
  img: `images/data-mining@2x.png`,
  pullImg: 'img-right',
  altText: `Data mining`,
  internalLink: true,
},
{
  header: `Execute actions and get notified when triggers are activated`,
  para: [`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque in libero eu nunc gravida laoreet. Sed est diam, lobortis vel dignissim et, finibus quis odio. Pellentesque sed nunc ipsum. Cras quis mi ac est tempus laoreet. Sed vel eros id lacus laoreet feugiat. Mauris vel ante sed nunc varius scelerisque ac vitae quam. Donec tempor, dui nec pretium sollicitudin, nibh felis luctus eros, id rhoncus neque est vel nunc. Nulla at odio eget dui dictum elementum in sit amet sem. In non nulla in diam lobortis faucibus. Vivamus viverra risus leo, vel porta nisi efficitur ac. Donec eu dignissim neque.`],
  img: `images/laboratorium@2x.png`,
  pullImg: 'img-left',
  altText: `Laboratorium`,
  btnPara: `See Projects`,
  internalLink: true,
},
{
  header: `Use wallets or exchanges API integration to automate execution`,
  para: [`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque in libero eu nunc gravida laoreet. Sed est diam, lobortis vel dignissim et, finibus quis odio. Pellentesque sed nunc ipsum. Cras quis mi ac est tempus laoreet. Sed vel eros id lacus laoreet feugiat. Mauris vel ante sed nunc varius scelerisque ac vitae quam. Donec tempor, dui nec pretium sollicitudin, nibh felis luctus eros, id rhoncus neque est vel nunc. Nulla at odio eget dui dictum elementum in sit amet sem. In non nulla in diam lobortis faucibus. Vivamus viverra risus leo, vel porta nisi efficitur ac. Donec eu dignissim neque.`],
  img: `images/exchanges.png`,
  pullImg: 'img-right',
  altText: `Exchanges`,
  btnPara: `See Projects`,
  internalLink: true,
}]